server:
  port: 8080
  error:
    path: /error
  servlet:
    session:
      timeout: 1
#    context-path: /chapter02
  tomcat:
    uri-encoding: utf-8
    max-threads: 500
    basedir: G:/workspace/path

book:
  name: 红楼梦
  author: 曹雪芹
  price: 30

filepath: G:/workspace/path/file

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: G:\\temp
      max-file-size: 1MB
      max-request-size: 100MB
      resolve-lazily: false
